const actionTypes = {
    phoneNumberActions: {
        GET_PHONENUMBER_START: "GET_PHONENUMBER_START",
        GET_PHONENUMBER_SUCCESS: "GET_PHONENUMBER_SUCCESS",
        GET_PHONENUMBER_FAIL: "GET_PHONENUMBER_FAIL",
        DELETE_PHONENUMBER_START: "DELETE_PHONENUMBER_START",
        DELETE_PHONENUMBER_SUCCESS: "DELETE_PHONENUMBER_SUCCESS",
        DELETE_PHONENUMBER_FAIL: "DELETE_PHONENUMBER_FAIL",
        ADD_PHONENUMBER: "ADD_PHONENUMBER",
        ADIT_PHONE:"ADIT_PHONE"
    },
    categoryActions: {
        GET_CATEGORİES_START: "GET_CATEGORİES_START",
        GET_CATEGORİES_SUCCESS: "GET_CATEGORİES_SUCCESS",
        GET_CATEGORİES_FAIL: "GET_CATEGORİES_FAIL"
     }
 }

export default actionTypes